#!/bin/bash

# Script to demonstrate commitizen usage
# This script shows how to make conventional commits

echo "GitHub Semantic Versioning Workflows - Commitizen Demo"
echo "======================================================"
echo ""
echo "This repository is set up with Commitizen to help you create conventional commits."
echo ""
echo "Usage:"
echo "  yarn commit    - Use Commitizen to create a conventional commit"
echo "  git cz         - Alternative command to use Commitizen"
echo ""
echo "Conventional commit types:"
echo "  feat:     A new feature"
echo "  fix:      A bug fix"
echo "  docs:     Documentation only changes"
echo "  style:    Changes that do not affect the meaning of the code"
echo "  refactor: A code change that neither fixes a bug nor adds a feature"
echo "  perf:     A code change that improves performance"
echo "  test:     Adding missing tests or correcting existing tests"
echo "  chore:    Changes to the build process or auxiliary tools"
echo ""
echo "Example commits:"
echo "  feat: add Docker build workflow"
echo "  fix: resolve issue with semantic-release configuration"
echo "  docs: update README with usage examples"
echo "  chore: bump dependencies to latest versions"
echo ""
echo "To get started:"
echo "1. Make some changes to your files"
echo "2. Stage your changes: git add ."
echo "3. Use Commitizen: yarn commit"
echo "4. Follow the prompts to create a conventional commit"
