name: PR Release Check (Simple)

on:
  pull_request:
    branches:
      - main
    types: [opened, synchronize, edited]

jobs:
  check-release:
    uses: ./.github/workflows/reusable-pr-release-check.yml
    secrets: inherit
